version: "3"

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3300:3300"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
